//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.JobService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Sourabh\\Examples\\PIMInnovation\\PIM\\PIM.JobService\\FileWatcher\\inbound\\")]
        public string loadPath {
            get {
                return ((string)(this["loadPath"]));
            }
            set {
                this["loadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Sourabh\\Examples\\PIMInnovation\\PIM\\PIM.JobService\\FileWatcher\\inprogress\\")]
        public string progressPath {
            get {
                return ((string)(this["progressPath"]));
            }
            set {
                this["progressPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/pimapi/api/")]
        public string apiUrl {
            get {
                return ((string)(this["apiUrl"]));
            }
            set {
                this["apiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Sourabh\\Examples\\PIMInnovation\\PIM\\PIM.JobService\\Logs")]
        public string logPath {
            get {
                return ((string)(this["logPath"]));
            }
            set {
                this["logPath"] = value;
            }
        }
    }
}
