//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PIM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PIM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PIM", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have the access in the tool please contact to administrator.
        /// </summary>
        internal static string accessError {
            get {
                return ResourceManager.GetString("accessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password.
        /// </summary>
        internal static string alertInvalidUserName {
            get {
                return ResourceManager.GetString("alertInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        internal static string alertNoRecordFound {
            get {
                return ResourceManager.GetString("alertNoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be between 8 and 20 characters..
        /// </summary>
        internal static string alertPasswordLength {
            get {
                return ResourceManager.GetString("alertPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain one lower &amp;amp; uppercase letter, and one non-alpha character (a number or a symbol.).
        /// </summary>
        internal static string alertPasswordRequirement {
            get {
                return ResourceManager.GetString("alertPasswordRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Workflow.
        /// </summary>
        internal static string btnCreateWorkflow {
            get {
                return ResourceManager.GetString("btnCreateWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO Login.
        /// </summary>
        internal static string btnSsoLogin {
            get {
                return ResourceManager.GetString("btnSsoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string btnUpload {
            get {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;html&amp;gt;
        ///&amp;lt;head&amp;gt;
        ///&amp;lt;/head&amp;gt;
        ///&amp;lt;body&amp;gt;
        ///    Dear {firstname} {lastname},
        ///    &amp;lt;br /&amp;gt;
        ///    &amp;lt;br /&amp;gt;
        ///    Click on the link to change your password : &amp;lt;a href=&quot;{link}&quot;&amp;gt;link&amp;lt;/a&amp;gt;
        ///    &amp;lt;br /&amp;gt;
        ///    &amp;lt;br /&amp;gt;
        ///    Regards,
        ///&amp;lt;/body&amp;gt;
        ///&amp;lt;/html&amp;gt;.
        /// </summary>
        internal static string emailPasswordRecovery {
            get {
                return ResourceManager.GetString("emailPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIM Tool Password Reset.
        /// </summary>
        internal static string emailSubjectPasswordRecovery {
            get {
                return ResourceManager.GetString("emailSubjectPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string headerDelete {
            get {
                return ResourceManager.GetString("headerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCM.
        /// </summary>
        internal static string headerPIM {
            get {
                return ResourceManager.GetString("headerPIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload DataModel.
        /// </summary>
        internal static string headerUploadDataModel {
            get {
                return ResourceManager.GetString("headerUploadDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid email.
        /// </summary>
        internal static string invalidEmail {
            get {
                return ResourceManager.GetString("invalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string labelNext {
            get {
                return ResourceManager.GetString("labelNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        internal static string labelPrevious {
            get {
                return ResourceManager.GetString("labelPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attribute.
        /// </summary>
        internal static string lblAddAttribute {
            get {
                return ResourceManager.GetString("lblAddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attribute Group.
        /// </summary>
        internal static string lblAddAttributeGroup {
            get {
                return ResourceManager.GetString("lblAddAttributeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Column.
        /// </summary>
        internal static string lblAddColumn {
            get {
                return ResourceManager.GetString("lblAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add LookUp Table.
        /// </summary>
        internal static string lblAddLookUp {
            get {
                return ResourceManager.GetString("lblAddLookUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Attribute.
        /// </summary>
        internal static string lblAddNewAttribute {
            get {
                return ResourceManager.GetString("lblAddNewAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Record.
        /// </summary>
        internal static string lblAddRecord {
            get {
                return ResourceManager.GetString("lblAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        internal static string lblAddRole {
            get {
                return ResourceManager.GetString("lblAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SubSection.
        /// </summary>
        internal static string lblAddsubsection {
            get {
                return ResourceManager.GetString("lblAddsubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        internal static string lblAddUser {
            get {
                return ResourceManager.GetString("lblAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Workflow.
        /// </summary>
        internal static string lblAddWorkflow {
            get {
                return ResourceManager.GetString("lblAddWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string lblAttribute {
            get {
                return ResourceManager.GetString("lblAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Group.
        /// </summary>
        internal static string lblAttributeGroup {
            get {
                return ResourceManager.GetString("lblAttributeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Master.
        /// </summary>
        internal static string lblAttributeMaster {
            get {
                return ResourceManager.GetString("lblAttributeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeType.
        /// </summary>
        internal static string lblAttributeType {
            get {
                return ResourceManager.GetString("lblAttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Rule.
        /// </summary>
        internal static string lblBusinessRule {
            get {
                return ResourceManager.GetString("lblBusinessRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string lblCatalog {
            get {
                return ResourceManager.GetString("lblCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string lblconNewPassword {
            get {
                return ResourceManager.GetString("lblconNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        internal static string lblCurrentStatus {
            get {
                return ResourceManager.GetString("lblCurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Local.
        /// </summary>
        internal static string lblDataLocal {
            get {
                return ResourceManager.GetString("lblDataLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string lblDataType {
            get {
                return ResourceManager.GetString("lblDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Role.
        /// </summary>
        internal static string lblDeleteRole {
            get {
                return ResourceManager.GetString("lblDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string lblDeleteUser {
            get {
                return ResourceManager.GetString("lblDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string lblDisabled {
            get {
                return ResourceManager.GetString("lblDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayType.
        /// </summary>
        internal static string lblDisplayType {
            get {
                return ResourceManager.GetString("lblDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization.
        /// </summary>
        internal static string lbleditOrg {
            get {
                return ResourceManager.GetString("lbleditOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        internal static string lblEditRecord {
            get {
                return ResourceManager.GetString("lblEditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        internal static string lblEditRole {
            get {
                return ResourceManager.GetString("lblEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string lblEditUser {
            get {
                return ResourceManager.GetString("lblEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Preferences.
        /// </summary>
        internal static string lblEditUserPref {
            get {
                return ResourceManager.GetString("lblEditUserPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddEntity.
        /// </summary>
        internal static string lblEntity {
            get {
                return ResourceManager.GetString("lblEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password?.
        /// </summary>
        internal static string lblForgetPassword {
            get {
                return ResourceManager.GetString("lblForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCatalog.
        /// </summary>
        internal static string lblIsCatalog {
            get {
                return ResourceManager.GetString("lblIsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsContainor.
        /// </summary>
        internal static string lblIsContainor {
            get {
                return ResourceManager.GetString("lblIsContainor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOrganization.
        /// </summary>
        internal static string lblIsOrganization {
            get {
                return ResourceManager.GetString("lblIsOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLocalizable.
        /// </summary>
        internal static string lblLocalizable {
            get {
                return ResourceManager.GetString("lblLocalizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongName.
        /// </summary>
        internal static string lblLongName {
            get {
                return ResourceManager.GetString("lblLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookUp Table Master.
        /// </summary>
        internal static string lbllookupMaster {
            get {
                return ResourceManager.GetString("lbllookupMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Role.
        /// </summary>
        internal static string lblMaintainRole {
            get {
                return ResourceManager.GetString("lblMaintainRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain User.
        /// </summary>
        internal static string lblMaintainuser {
            get {
                return ResourceManager.GetString("lblMaintainuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string lblManager {
            get {
                return ResourceManager.GetString("lblManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Work Items.
        /// </summary>
        internal static string lblMyWorkItems {
            get {
                return ResourceManager.GetString("lblMyWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string lblOrganization {
            get {
                return ResourceManager.GetString("lblOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Organization and Container.
        /// </summary>
        internal static string lblOrgHeader {
            get {
                return ResourceManager.GetString("lblOrgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartNumber.
        /// </summary>
        internal static string lblPartNumber {
            get {
                return ResourceManager.GetString("lblPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        internal static string lblPlant {
            get {
                return ResourceManager.GetString("lblPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string lblRequired {
            get {
                return ResourceManager.GetString("lblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string lblRoleName {
            get {
                return ResourceManager.GetString("lblRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Searches.
        /// </summary>
        internal static string lblSavedSearched {
            get {
                return ResourceManager.GetString("lblSavedSearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design or Part or GTIN.
        /// </summary>
        internal static string lblscentity {
            get {
                return ResourceManager.GetString("lblscentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblSearchCriteria {
            get {
                return ResourceManager.GetString("lblSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Panel.
        /// </summary>
        internal static string lblSearchPanel {
            get {
                return ResourceManager.GetString("lblSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sgid.
        /// </summary>
        internal static string lblSgid {
            get {
                return ResourceManager.GetString("lblSgid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortName.
        /// </summary>
        internal static string lblShortName {
            get {
                return ResourceManager.GetString("lblShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowAt Creation.
        /// </summary>
        internal static string lblShowAtCreation {
            get {
                return ResourceManager.GetString("lblShowAtCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string lblSignOut {
            get {
                return ResourceManager.GetString("lblSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOA.
        /// </summary>
        internal static string lblSoa {
            get {
                return ResourceManager.GetString("lblSoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO Connection.
        /// </summary>
        internal static string lblSsoCon {
            get {
                return ResourceManager.GetString("lblSsoCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepName.
        /// </summary>
        internal static string lblStepName {
            get {
                return ResourceManager.GetString("lblStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        internal static string lblTableName {
            get {
                return ResourceManager.GetString("lblTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy.
        /// </summary>
        internal static string lblTaxonomy {
            get {
                return ResourceManager.GetString("lblTaxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone.
        /// </summary>
        internal static string lblTimeZone {
            get {
                return ResourceManager.GetString("lblTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Local.
        /// </summary>
        internal static string lblUILocal {
            get {
                return ResourceManager.GetString("lblUILocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string lblUsers {
            get {
                return ResourceManager.GetString("lblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string lblView {
            get {
                return ResourceManager.GetString("lblView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Name.
        /// </summary>
        internal static string lblWorkflowName {
            get {
                return ResourceManager.GetString("lblWorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Managment.
        /// </summary>
        internal static string menuAttribute {
            get {
                return ResourceManager.GetString("menuAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DataModel.
        /// </summary>
        internal static string menuExportDataModel {
            get {
                return ResourceManager.GetString("menuExportDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import DataModel.
        /// </summary>
        internal static string menuImportDataModel {
            get {
                return ResourceManager.GetString("menuImportDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        internal static string menuIntegration {
            get {
                return ResourceManager.GetString("menuIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Jobs.
        /// </summary>
        internal static string menuInterationJobs {
            get {
                return ResourceManager.GetString("menuInterationJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterData.
        /// </summary>
        internal static string menuMasters {
            get {
                return ResourceManager.GetString("menuMasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDM Model.
        /// </summary>
        internal static string menuModel {
            get {
                return ResourceManager.GetString("menuModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Chart.
        /// </summary>
        internal static string menuOrgChart {
            get {
                return ResourceManager.GetString("menuOrgChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Managment.
        /// </summary>
        internal static string menuRole {
            get {
                return ResourceManager.GetString("menuRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterData Managment.
        /// </summary>
        internal static string menuSysAdmin {
            get {
                return ResourceManager.GetString("menuSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Managment.
        /// </summary>
        internal static string menuUser {
            get {
                return ResourceManager.GetString("menuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Management.
        /// </summary>
        internal static string menuWorkflow {
            get {
                return ResourceManager.GetString("menuWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this record?.
        /// </summary>
        internal static string msgDelete {
            get {
                return ResourceManager.GetString("msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string optionNo {
            get {
                return ResourceManager.GetString("optionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string optionYes {
            get {
                return ResourceManager.GetString("optionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        internal static string titleChangeLog {
            get {
                return ResourceManager.GetString("titleChangeLog", resourceCulture);
            }
        }
    }
}
