export const environment = {
  production: true,
  api:{
    endPoint:'http://localhost/pimapi/api'
  },
  CasLoginUrl :'https://uat.websso.saint-gobain.com/cas/login',
  CasLogoutUrl : 'https://uat.websso.saint-gobain.com/cas/logout',
  loginUrl : "http://localhost/pim/login",
  authentication_url : 'authenticate',
  sso_url : 'sso',
  language_url : 'languages',
  role_url : 'roles',
  manager_url : 'managers',
  Category_url  :'categories',
  Org_url  :'enviroment',
  Catalog_url  :'catalogs',
  Taxonomy_url  :'taxonomy',
  TimeZone_url  :'timeZone',
  userPref_url  :'UserPrefrences',
  ldap_url  :'SearchUser',
  login_url  :'login',
  passwordRecovery_url  :'passwordRecovery',
  changePassword_url  :'changePassword',
  file_url  :'file',
  exportDataModel_url  :'dataModel',
  getSheet_url  :'getSheets',
  dataType_url:'dataType',
  displayType_url:'displayType',
  attributeType_url:'attributeTypes',
  attributeGroup_url:'attributeGroup'
};
